### ISSUE TITLE
AWS Java SDK out of date

### ISSUE THREAD

**Issue by moneymikeMD** [BroadleafCommerce/blc-amazon#11]
The plugin in pulling in version 1.9.x of the aws-java-sdk. This is causing this exception when using it:
```Caused by: java.lang.IllegalStateException: Socket not created by this factory
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3737)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1462)
        at org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProvider.addOrUpdateResourcesInternal(S3FileServiceProvider.java:173)
        at org.broadleafcommerce.vendor.amazon.s3.S3FileServiceProvider.addOrUpdateResourcesForPaths(S3FileServiceProvider.java:152)
        at org.broadleafcommerce.common.file.service.BroadleafFileServiceImpl.addOrUpdateResourcesForPaths(BroadleafFileServiceImpl.java:295)
        at org.broadleafcommerce.common.file.service.BroadleafFileServiceImpl.addOrUpdateResourceForPath(BroadleafFileServiceImpl.java:268)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl.saveBundle(ResourceBundlingServiceImpl.java:323)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl$1.doInLock(ResourceBundlingServiceImpl.java:240)
        at de.jkeylockmanager.manager.implementation.lockstripe.StripedKeyLockManager$1.doInLock(StripedKeyLockManager.java:77)
        at de.jkeylockmanager.manager.implementation.lockstripe.StripedKeyLockManager.executeLockedInternal(StripedKeyLockManager.java:99)
        at de.jkeylockmanager.manager.implementation.lockstripe.StripedKeyLockManager.executeLocked(StripedKeyLockManager.java:75)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl.createBundleIfNeeded(ResourceBundlingServiceImpl.java:232)
        at org.broadleafcommerce.common.resource.service.ResourceBundlingServiceImpl.resolveBundleResourceName(ResourceBundlingServiceImpl.java:184)
        at org.broadleafcommerce.common.web.processor.ResourceBundleProcessor.getReplacementModel(ResourceBundleProcessor.java:160)
        at org.broadleafcommerce.presentation.thymeleaf3.dialect.DelegatingThymeleaf3TagReplacementProcessor.doProcess(DelegatingThymeleaf3TagReplacementProcessor.java:48)
        at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
        ... 137 common frames omitted
```

The pom should be updated to the latest (1.11.170) and tested.

**Comment by phillipuniverse** [comment]
Thanks for the report!  Which version of this S3 plugin were you using?

**Comment by moneymikeMD** [comment]
We're using 2.0.x
